#!/bin/bash
set -e

ARCH=${ARCH:-"amd64"}

source $(dirname $0)/version

cd $(dirname $0)/..

if [ ! -e bin/rancher-flat-ipam ]; then
    ./scripts/build
fi

mkdir -p dist/artifacts
cd bin/

tar cvzf ../dist/artifacts/rancher-flat-ipam-${ARCH}-${VERSION}.tar.gz .

echo "Built rancher-flat-ipam-${ARCH}-${VERSION}.tar.gz"
